import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Languages, Sun } from "lucide-react";
import { Button } from "@/components/ui";
import Link from "next/link";
import { Toaster } from "sonner";

import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}   ${geistMono.variable} antialiased`}>
        <Toaster richColors></Toaster>
        <header className="py-4 flex container mx-auto">
          <div className="flex space-x-2">
            <Button
              asChild
              variant="secondary">
              <Link href="/character">캐릭터 관리</Link>
            </Button>
            <Button
              asChild
              variant="secondary">
              <Link href="/character">데미지 계산</Link>
            </Button>
            <Button variant="secondary">
              <Link href="/switch-point">이전 포인트 계산</Link>
            </Button>{" "}
            <Button variant="secondary">
              <Link href="/character3">협동 타이머</Link>
            </Button>
          </div>
          <div className="ml-auto flex w-max space-x-4">
            <Button
              variant="secondary"
              size="icon"
              className="size-8">
              <Languages />
            </Button>
            <Button
              variant="secondary"
              size="icon"
              className="size-8">
              <Sun />
            </Button>
          </div>
        </header>
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}
